# An√°lisis y manipulaci√≥n de datos

In [1]:
# Se importan las librer√≠as que se van a utilizar

import pandas as pd
import re
import pickle as pk

# setting Jupyter

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',200)
pd.options.display.float_format= '{:.2f}'.format

### Estructura de datos

In [2]:
#Se importa el diccionario creado en el archivo anterior
tweets = pk.load(open('../../data/data_a_procesar/Tweets','rb'))
tweets[0]

{'Autor_id': 1135944345591394304,
 'Usuario': 'MaldonadoPoty',
 'Seguidores_autor': 148,
 'Tweets_autor': 2497,
 'Descripcion_autor': '',
 'Locacion_autor': None,
 'Texto': '*Te ganar√°s la vacuna con el sudor de tu frente*\nBajo una l√≥gica cruel e inhumana, la empresa Rappi Colombia desafi√≥ a sus ‚Äúcolaboradores‚Äù para que compitan por una vacuna contra la covid.\nhttps://t.co/pqgeNKoE3c https://t.co/ER295HOma4',
 'Fecha': datetime.datetime(2021, 6, 30, 23, 41, 36, tzinfo=datetime.timezone.utc),
 'Retweets': 0,
 'Respuestas': 0,
 'Likes': 1,
 'Cant_citas': 0,
 'Fuente': 'Twitter for Android'}

In [3]:
# Tranformar el diccionario en un DataFrame
df = pd.DataFrame(tweets)
df.head()

,Autor_id,Usuario,Seguidores_autor,Tweets_autor,Descripcion_autor,Locacion_autor,Texto,Fecha,Retweets,Respuestas,Likes,Cant_citas,Fuente
0,1135944345591394304,MaldonadoPoty,148,2497,,None,*Te ganar√°s la vacuna con el sudor de tu frent...,2021-06-30 23:41:36+00:00,0,0,1,0,Twitter for Android
1,1048219845987323905,MikeEhrmantrau5,48,1393,üòë,"Albuquerque, La Matanza",@ErwinSchrdngr @buccinito @Dianacos @msalnacio...,2021-06-30 23:24:12+00:00,1,1,5,0,Twitter for Android
2,3376611622,agabrielav27,5027,36925,Mam√° feliz.. Amo las cosas simples de la vida ...,"Jujuy, Argentina",Despu√©s de la vacuna contra covid aconsejan no...,2021-06-30 23:04:50+00:00,1,0,1,0,Twitter for Android
3,134477385,ingmatiasvenier,1365,13298,"Ingeniero Agr√≥nomo,MSc Viticultura&Enolog√≠a,√≠t...",Gral. San Mart√≠n - Mendoza,Presidente de la Nacion: Vacuna COVID para men...,2021-06-30 22:23:17+00:00,0,0,0,0,Twitter for iPhone
4,335918975,edgar702010,4167,70406,Si no sueltas el pasado con qu√© manos agarras ...,"R√≠o Grande, Argentina",@maximilianoreyz @alferdez @EstadioAzteca @Car...,2021-06-30 22:22:27+00:00,0,0,0,0,Twitter for Android

In [4]:
# Tipo de datos
df.dtypes

Autor_id                           int64
Usuario                           object
Seguidores_autor                   int64
Tweets_autor                       int64
Descripcion_autor                 object
Locacion_autor                    object
Texto                             object
Fecha                datetime64[ns, UTC]
Retweets                           int64
Respuestas                         int64
Likes                              int64
Cant_citas                         int64
Fuente                            object
dtype: object

## Entendimineto de datos

In [5]:
# Filas y columnas
print(f'En este Dataset hay {df.shape[0]} filas y {df.shape[1]} columnas.')

En este Dataset hay 3010 filas y 13 columnas.

In [6]:
df['Texto'].head(20)

0     *Te ganar√°s la vacuna con el sudor de tu frent...
1     @ErwinSchrdngr @buccinito @Dianacos @msalnacio...
2     Despu√©s de la vacuna contra covid aconsejan no...
3     Presidente de la Nacion: Vacuna COVID para men...
4     @maximilianoreyz @alferdez @EstadioAzteca @Car...
5     Ser funcionario te protege m√°s  contra el COVI...
6     Si les interesa saber sobre las vacunas cubana...
7     Hoy Es Un Muy Pero Muy Hermoso Dia üòÄüòÄü•≥ü•≥üòäüòä: Mi ...
8     @elbosnio @ngadano Te lo resumo: "ellos" no so...
9     Llegu√© a la primer dosis de vacuna sin haberme...
10    @Baneste_lab @JosefinaCanale @ergasto Eso no e...
11    Presidente de la Nacion: Vacuna COVID para men...
12    @CamilaM37706694 @FVoraces @NikMartini @MDSuar...
13    Con mucha emoci√≥n y alegr√≠a hoy recib√≠ mi prim...
14    Hoy llegaron much√≠simos SMS para confirmar tur...
15    Presidente de la Naci√≥n: Vacuna COVID para men...
16    Ya vacunado contra el covid-19 gracias a los c...
17    @BonzoWow @PatoBullrich Si todos vienen de vac...
18    Quiero confirmar que los efectos secundarios d...
19    Presidente de la Nacion: Vacuna COVID para men...
Name: Texto, dtype: object

In [7]:
df['Locacion_autor'].value_counts()[:10]

Locacion_autor
Buenos Aires, Argentina           183
Ciudad Aut√≥noma de Buenos Aire    172
Argentina                         142
C√≥rdoba, Argentina                 74
Rosario, Argentina                 58
Buenos Aires                       40
La Plata, Argentina                39
Campana, Argentina                 31
Rep√∫blica Argentina                28
argentina                          26
Name: count, dtype: int64

In [8]:
df['Locacion_autor'].value_counts().shape[0]

782

In [9]:
df['Descripcion_autor'].tail(20)

2990    üë©üèª‚Äçüíª Directora y Agente de Prensa en @dosdosun...
2991    liberal.  Agn√≥stico. Roquista. Fana del rugby ...
2992    cumplea√±os 13 de agosto .leonina y de Racing.q...
2993
2994
2995                             Decoradora de interiores
2996    Fundador de ¬®El Baqueano¬®, ‚ÄúCocina SIN Fronter...
2997    estoy en una etapa donde para ofenderme, prime...
2998    Odont√≥loga .Directora general de  D.Humanos de...
2999    Odont√≥loga .Directora general de  D.Humanos de...
3000    üá¶üá∑\nLas 24 horas leo Pol√≠tica, pienso Pol√≠tica...
3001    Argentina, fan√°tica de mi hijo, de River, amo ...
3002    Estudiante de Ciencias de la Educaci√≥n UNLP\nT...
3003                     Nacido aqu√≠,y sigo viviendo aqu√≠
3004    |Roni / Judio Runner y Sionista. . Larga Vida ...
3005    Me parece una pelotudes que se tomen a Twitter...
3006
3007
3008    cumplea√±os 13 de agosto .leonina y de Racing.q...
3009    El Estado no es la soluci√≥n, es el problema. L...
Name: Descripcion_autor, dtype: object

In [10]:
df['Fecha'].head(10)

0   2021-06-30 23:41:36+00:00
1   2021-06-30 23:24:12+00:00
2   2021-06-30 23:04:50+00:00
3   2021-06-30 22:23:17+00:00
4   2021-06-30 22:22:27+00:00
5   2021-06-30 22:09:39+00:00
6   2021-06-30 21:29:56+00:00
7   2021-06-30 19:05:20+00:00
8   2021-06-30 17:57:44+00:00
9   2021-06-30 17:38:45+00:00
Name: Fecha, dtype: datetime64[ns, UTC]

In [12]:
# Ratio de unicidad
def uniqueRate(data,initialColumn):    
  d = pd.DataFrame(columns=["Cantidad_√∫nicos","Ratio_√∫nicos"],index=data.columns)
  x = data.columns

  for i in data.columns:
    d.loc[i,"Cantidad_√∫nicos"]=data[i].nunique()

  d["Ratio_√∫nicos"]= d["Cantidad_√∫nicos"] / data.shape[0]
  d["Ratio_√∫nicos"] = d["Ratio_√∫nicos"].astype(float) *100
  d["Ratio_√∫nicos"] = round(d["Ratio_√∫nicos"],2).astype(str) + "%"
  return d.sort_values(by="Cantidad_√∫nicos",ascending=False)


uniqueRate(df,0)

                  Cantidad_√∫nicos Ratio_√∫nicos
Fecha                        3007        99.9%
Texto                        2999       99.63%
Autor_id                     2047       68.01%
Usuario                      2047       68.01%
Tweets_autor                 1983       65.88%
Descripcion_autor            1791        59.5%
Seguidores_autor             1377       45.75%
Locacion_autor                782       25.98%
Likes                         107        3.55%
Retweets                       57        1.89%
Respuestas                     37        1.23%
Cant_citas                     20        0.66%
Fuente                          7        0.23%

In [13]:
# Fuente
df['Fuente'].value_counts()

Fuente
Twitter for Android    2367
Twitter for iPhone      486
Instagram                63
dlvr.it                  48
Twitter for iPad         44
Foursquare Swarm          1
Foursquare                1
Name: count, dtype: int64

In [14]:
# Desarrollo del Tweet
df['Texto'].value_counts().head(10)

Texto
Vacuna contra el COVID-19 podr√≠a aplicarse para la esclerosis m√∫ltiple https://t.co/fMQEQTcTHT v√≠a @uchile                                                                                                           3
El Papa Francisco recibi√≥ la primer dosis de la vacuna contra el Covid-19 https://t.co/XdmElTdGpo                                                                                                                    2
Prioridad en la vacuna COVID a las personas con discapacidad @carlavizzotti @msalnacion @CarlaCa... https://t.co/4rP8P5xXSJ v√≠a @ChangeorgAR                                                                         2
Millonaria argentina se vacuna en #EstadosUnidos y termina en "hotel sanitario" porte√±o por #COVID https://t.co/nAuwzPTX0a https://t.co/oevEweCS6x                                                                   2
Per√∫ anunci√≥ acuerdos de compra de la vacuna contra el COVID-19 con AstraZeneca y Sinopharm - Infobae https://t.co/oczaotUez7                                                                                        2
El #PapaFrancisco, de 84 a√±os, recibi√≥ la segunda dosis de la #vacuna contra el #coronavirus y est√° inmunizado, confirm√≥ a Efe el portavoz Vaticano, Matteo Bruni https://t.co/Pv9CFD06Jy https://t.co/jOYoS4SzCo    2
Presidente de la Nacion: Vacuna COVID para menores con discapacidad @ANMATsalud @carlavizzotti @SandraMTirado @fggalarraga @andiscapacidad - ¬°Firm√° la petici√≥n! https://t.co/He9R0Fs96G v√≠a @ChangeorgAR            2
Presidente de la Nacion: Vacuna COVID para menores con discapacidad @ANMATsalud @carlavizzotti @SandraMTirado @fggalarraga @andiscapacidad - ¬°Firm√° la petici√≥n! https://t.co/enFsaifwU2 v√≠a @ChangeorgAR            2
Presidente de la Nacion: Vacuna COVID para menores con discapacidad @ANMATsalud @carlavizzotti @SandraMTirado @fggalarraga @andiscapacidad - ¬°Firm√° la petici√≥n! https://t.co/ooBde4NgZW v√≠a @ChangeorgAR            2
CABA: a partir del viernes, los mayores de 80 a√±os podr√°n anotarse para recibir la vacuna contra el COVID-19 - Infobae https://t.co/zrvnRYyDiA                                                                       2
Name: count, dtype: int64

In [15]:
firma=df[df['Texto'].str.contains('¬°Firm√° la petici√≥n!')]
infobae=df[df['Texto'].str.contains('Infobae')]
print(f'Existen {firma.shape[0]} registros con el texto "Firm√° la petici√≥n"')
print(f'Existen {infobae.shape[0]} registros con el texto "Infobae"')

Existen 110 registros con el texto "Firm√° la petici√≥n"
Existen 48 registros con el texto "Infobae"

In [16]:
# Usuario
df['Usuario'].value_counts()

Usuario
Mario_Moray        40
ElsaKekita         28
LADdigital         28
adapd1             28
dariomaceiras1     23
                   ..
soyunpugcarlino     1
julymar0721         1
flavioarandatw      1
SilvinaMGomez       1
patriciolauda       1
Name: count, Length: 2047, dtype: int64

In [17]:
# An√°lisis del usuario "Mario_Moray" el cual es quien mayor cantidad de tweets postea realcionado a este tema.
df[df['Autor_id']==246107898].head()

,Autor_id,Usuario,Seguidores_autor,Tweets_autor,Descripcion_autor,Locacion_autor,Texto,Fecha,Retweets,Respuestas,Likes,Cant_citas,Fuente
20,246107898,Mario_Moray,11356,87990,"Producer & Senior Editor. #BreakingNews, #News...","Buenos Aires, Argentina",#Putin ha declarado que se vacun√≥ con la #Sput...,2021-06-30 09:32:09+00:00,0,0,0,0,Twitter for iPad
42,246107898,Mario_Moray,11356,87990,"Producer & Senior Editor. #BreakingNews, #News...","Buenos Aires, Argentina",Qui√©nes pueden vacunarse sin turno en la provi...,2021-06-29 14:30:56+00:00,0,0,0,0,Twitter for iPad
136,246107898,Mario_Moray,11356,87990,"Producer & Senior Editor. #BreakingNews, #News...","Buenos Aires, Argentina",Confirmado: si tuviste #COVID19 solo necesitas...,2021-06-24 12:36:21+00:00,0,0,0,0,Twitter for iPad
772,246107898,Mario_Moray,11356,87990,"Producer & Senior Editor. #BreakingNews, #News...","Buenos Aires, Argentina",Vacunados con dos dosis de la #SputnikV (.@spu...,2021-05-27 22:30:58+00:00,0,0,2,0,Twitter for iPad
787,246107898,Mario_Moray,11356,87990,"Producer & Senior Editor. #BreakingNews, #News...","Buenos Aires, Argentina",El Gobierno alcanz√≥ un acuerdo para la compra ...,2021-05-27 09:00:10+00:00,0,1,0,0,Twitter for iPad

In [18]:
# He notado que en la "descipci√≥n del autor" es posible reconocer a algunos autores que utilizan la plataforma para informar.
# Por lo tanto, he eliminado esos usuarios para realizar el an√°lisis s√≥lo con tweets que expresan opini√≥n p√∫bloca. 
# Dicha limpieza le hecho identificando palabras como "Noticias", "Revista", "Diario" y "News". Aquellos autores que presentan esas palabras en su descripci√≥n, quedar√°n duera de este an√°lisis.

df1 = df.copy()
df1['Descripcion_autor'] = df1.Descripcion_autor.str.upper()
print('Cantidad de tweets que se eliminar√≠an por palabra clave:\n')
print(f"Noticia -> {df1[df1['Descripcion_autor'].str.contains('NOTICIAS')].shape[0]}")
print(f"Revista -> {df1[df1['Descripcion_autor'].str.contains('REVISTA')].shape[0]}")
print(f"Diario -> {df1[df1['Descripcion_autor'].str.contains('DIARIO')].shape[0]}")
print(f"News -> {df1[df1['Descripcion_autor'].str.contains('NEWS')].shape[0]}")

Cantidad de tweets que se eliminar√≠an por palabra clave:

Noticia -> 76
Revista -> 4
Diario -> 61
News -> 42

In [19]:
df1 = df.copy()
df1['Texto'] = df1.Texto.str.upper()
print('Cantidad de tweets que se eliminar√≠an por palabra clave:\n')
print(f"¬°Firm√° la petici√≥n! -> {df['Texto'].str.contains('¬°Firm√° la petici√≥n!').sum()}")

Cantidad de tweets que se eliminar√≠an por palabra clave:

¬°Firm√° la petici√≥n! -> 110

## Primeras conclusiones:


* Cambios en la columna Fecha: Se elimina el componente correspondiente a la hora en este campo. √∫nicamnete se mantiene la fecha, con formato "aaa-mm-dd".
* Se crea una nueva variable llamada "Hora" que captura la hora en la que el tweet fue creado
* Se crea otra nueva variable llamada "Mes" que registra √∫nicamente el mes en le que el tweet fue creado.
* Se eliminan los tweets en donde la descripci√≥n del ususario contenga las siguientes palabras clave:
>* Revista
>* Diario
>* Noticias
>* News
* Se eliminan los tweets manifiesten en su contenido la palabra clave "¬°Firm√° la petici√≥n!"
* Se eliminan los tweets que fueron creados mediante la siguiente fuente: 
>* dlvr.it
>* Foursquare Swarm
>* Foursquare

## Limpieza de  datos

In [20]:
# Cambios en la columna "Fecha".

df['Fecha'] = df['Fecha'].astype(str)
df['Hora']  = df.Fecha.str[10:13] + "hs" #Se crea una columna nueva para saber la hora en la que se cre√≥ el tweet
df['Mes']  = df.Fecha.str[5:7] #Se crea una columna nueva para saber la hora en la que se cre√≥ el tweet
df['Fecha']  = df.Fecha.str[0:10] #Se crea una columna para extraer s√≥lo la fecha de la craci√≥n del tweet
df['Fecha']= df['Fecha'].apply(pd.to_datetime)

di={'01':'Enero','03':'Marzo','02':'Febrero','04':'Abril','05':'Mayo','06':'Junio'}
df.replace({'Mes':di},inplace=True)
df.head()

,Autor_id,Usuario,Seguidores_autor,Tweets_autor,Descripcion_autor,Locacion_autor,Texto,Fecha,Retweets,Respuestas,Likes,Cant_citas,Fuente,Hora,Mes
0,1135944345591394304,MaldonadoPoty,148,2497,,None,*Te ganar√°s la vacuna con el sudor de tu frent...,2021-06-30,0,0,1,0,Twitter for Android,23hs,Junio
1,1048219845987323905,MikeEhrmantrau5,48,1393,üòë,"Albuquerque, La Matanza",@ErwinSchrdngr @buccinito @Dianacos @msalnacio...,2021-06-30,1,1,5,0,Twitter for Android,23hs,Junio
2,3376611622,agabrielav27,5027,36925,Mam√° feliz.. Amo las cosas simples de la vida ...,"Jujuy, Argentina",Despu√©s de la vacuna contra covid aconsejan no...,2021-06-30,1,0,1,0,Twitter for Android,23hs,Junio
3,134477385,ingmatiasvenier,1365,13298,"Ingeniero Agr√≥nomo,MSc Viticultura&Enolog√≠a,√≠t...",Gral. San Mart√≠n - Mendoza,Presidente de la Nacion: Vacuna COVID para men...,2021-06-30,0,0,0,0,Twitter for iPhone,22hs,Junio
4,335918975,edgar702010,4167,70406,Si no sueltas el pasado con qu√© manos agarras ...,"R√≠o Grande, Argentina",@maximilianoreyz @alferdez @EstadioAzteca @Car...,2021-06-30,0,0,0,0,Twitter for Android,22hs,Junio

In [21]:
df.shape

(3010, 15)

In [22]:
df['Descripcion_autor']=df.Descripcion_autor.str.upper()

words=['REVISTA','DIARIO','NOTICIA','NEWS']

for word in words:
    df=df.drop(df[(df['Descripcion_autor'].str.contains(word))].index)


words2=['¬°Firm√° la petici√≥n!','Infobae']

for word2 in words2:
    df=df.drop(df[(df['Texto'].str.contains(word2))].index)


words3=['dlvr.it','Foursquare Swarm','Foursquare']

for word3 in words3:
    df=df.drop(df[(df['Fuente']==word3)].index)

## Limpieza de datos - Texto

In [23]:
# Se crea una funci√≥n para limpiar el texto presente en los tweets
def LimpiarTexto(texto):
    texto = re.sub('@[A-Za-z0‚Äì9]+', '', texto) # Eliminar "#" del texto
    texto = re.sub('#', '', texto) # Eliminar hashtags (#)
    texto = re.sub('@[\S]*', '', texto) #Eliminar menciones (@)
    texto = re.sub('\\n', '', texto) # Eliminar el caracter '\n'
    texto = re.sub('https?:\/\/\S+', '', texto) # Eliminar Hiperlinks (https:\)
    return texto

# Limpieza de tweets
df['Texto'] = df['Texto'].apply(LimpiarTexto)
df['Texto'] = df['Texto'].str.strip()
df['Texto'] = df['Texto'].str.strip('*')

In [24]:
df = df.reset_index()
#Nueva Variable: Cantidad de caracteres en un Tweet

longitud=[]
for i in range(0,len(df.Texto)):
    longitud.append(len(df.Texto[i]))

df['Long_Texto'] = longitud

In [25]:
df.head()

,index,Autor_id,Usuario,Seguidores_autor,Tweets_autor,Descripcion_autor,Locacion_autor,Texto,Fecha,Retweets,Respuestas,Likes,Cant_citas,Fuente,Hora,Mes,Long_Texto
0,0,1135944345591394304,MaldonadoPoty,148,2497,,None,Te ganar√°s la vacuna con el sudor de tu frente...,2021-06-30,0,0,1,0,Twitter for Android,23hs,Junio,186
1,1,1048219845987323905,MikeEhrmantrau5,48,1393,üòë,"Albuquerque, La Matanza","""Adem√°s, al momento, constat√≥ que s√≥lo falleci...",2021-06-30,1,1,5,0,Twitter for Android,23hs,Junio,196
2,2,3376611622,agabrielav27,5027,36925,MAM√Å FELIZ.. AMO LAS COSAS SIMPLES DE LA VIDA ...,"Jujuy, Argentina",Despu√©s de la vacuna contra covid aconsejan no...,2021-06-30,1,0,1,0,Twitter for Android,23hs,Junio,146
3,4,335918975,edgar702010,4167,70406,SI NO SUELTAS EL PASADO CON QU√â MANOS AGARRAS ...,"R√≠o Grande, Argentina",QUE EL MUNDO SEPA QUIENES SON UDS. LACRASSer f...,2021-06-30,0,0,0,0,Twitter for Android,22hs,Junio,104
4,5,2740303732,guoltPE,4744,64684,PUEDES ENGA√ëAR A TODO EL MUNDO ALG√öN TIEMPO. P...,"La Plata, Argentina",Ser funcionario te protege m√°s contra el COVI...,2021-06-30,0,1,2,0,Twitter for Android,22hs,Junio,70

In [26]:
# Se eliminan las columnas que no se van a utilizar

df.drop(columns=['index','Autor_id','Usuario','Descripcion_autor','Locacion_autor'],inplace=True)

In [27]:
df.head()

,Seguidores_autor,Tweets_autor,Texto,Fecha,Retweets,Respuestas,Likes,Cant_citas,Fuente,Hora,Mes,Long_Texto
0,148,2497,Te ganar√°s la vacuna con el sudor de tu frente...,2021-06-30,0,0,1,0,Twitter for Android,23hs,Junio,186
1,48,1393,"""Adem√°s, al momento, constat√≥ que s√≥lo falleci...",2021-06-30,1,1,5,0,Twitter for Android,23hs,Junio,196
2,5027,36925,Despu√©s de la vacuna contra covid aconsejan no...,2021-06-30,1,0,1,0,Twitter for Android,23hs,Junio,146
3,4167,70406,QUE EL MUNDO SEPA QUIENES SON UDS. LACRASSer f...,2021-06-30,0,0,0,0,Twitter for Android,22hs,Junio,104
4,4744,64684,Ser funcionario te protege m√°s contra el COVI...,2021-06-30,0,1,2,0,Twitter for Android,22hs,Junio,70

In [28]:
df.drop_duplicates(subset=['Texto'], keep='last',inplace=True)

In [29]:
print(f"Cantidad de registros restantes: {df.shape[0]}")

Cantidad de registros restantes: 2599

## Estad√≠sitica Descriptiva

In [30]:
num = df[['Seguidores_autor','Tweets_autor','Retweets','Respuestas','Likes','Cant_citas','Long_Texto']]
num.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Seguidores_autor,2599.00,4171.53,24542.96,0.00,226.00,717.00,2286.00,557476.00
Tweets_autor,2599.00,43275.47,137983.61,3.00,3791.00,12528.00,37819.00,1701543.00
Retweets,2599.00,2.49,24.60,0.00,0.00,0.00,1.00,977.00
Respuestas,2599.00,1.35,21.18,0.00,0.00,0.00,1.00,968.00
Likes,2599.00,13.63,298.42,0.00,0.00,1.00,3.00,15026.00
Cant_citas,2599.00,0.22,2.31,0.00,0.00,0.00,0.00,89.00
Long_Texto,2599.00,170.91,72.79,6.00,107.00,170.00,239.00,298.00

In [31]:
df.groupby(['Mes'])[['Retweets','Likes','Respuestas']].sum()

         Retweets  Likes  Respuestas
Mes
Abril        1244   4859         712
Enero         984   3246         262
Febrero       808   2811         330
Junio         966   4387         627
Marzo        1218   3763         451
Mayo         1263  16347        1127

In [32]:
df.groupby(['Mes'])[['Seguidores_autor','Tweets_autor']].mean()

         Seguidores_autor  Tweets_autor
Mes
Abril             2594.46      41388.55
Enero             7892.98     106391.54
Febrero           4007.19      35738.44
Junio             3994.44      30803.07
Marzo             5650.03      34421.42
Mayo              2405.45      27370.04

In [33]:
df.groupby(['Mes'])['Seguidores_autor'].count()

Mes
Abril      555
Enero      327
Febrero    385
Junio      562
Marzo      364
Mayo       406
Name: Seguidores_autor, dtype: int64

In [34]:
df['Hora'].value_counts()#.orderby('index')

Hora
 14hs    176
 17hs    170
 16hs    168
 18hs    165
 23hs    165
 15hs    156
 01hs    151
 00hs    151
 21hs    144
 22hs    142
 19hs    135
 02hs    133
 20hs    132
 12hs    131
 13hs    130
 11hs     95
 03hs     86
 04hs     48
 10hs     38
 05hs     32
 09hs     16
 08hs     13
 06hs     12
 07hs     10
Name: count, dtype: int64

In [35]:
Texto = df['Texto']
# Se guarda el que s√≥lo contiene el texto del twit para relaizar un an√°lisis de sentiminetos
Texto.to_csv('../../data/data_a_procesar/Texto.csv',index=False)

# Se guarda el DataFrame completo para un posterior an√°lisis final
df.to_csv('../../data/data_procesada/twitts.csv',index=False)